import { Geist, Geist_Mono } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import { AuthProvider } from '../components/providers/AuthProvider'
import { QueryProvider } from '../components/providers/QueryProvider'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} scroll-smooth font-mono antialiased`}
      >
        {/* 1. Header / Menu */}
        <QueryProvider>
          <AuthProvider>
            {children}
            <Toaster
              position='top-right'
              toastOptions={{
                duration: 4000,
                style: {
                  background: '#363636',
                  color: '#fff'
                },
                success: {
                  duration: 3000,
                  theme: {
                    primary: '#4ade80'
                  }
                },
                error: {
                  duration: 5000,
                  theme: {
                    primary: '#ef4444'
                  }
                }
              }}
            />
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  )
}
